name: Release

on:
  push:
    tags:
      - "[0-9]+.[0-9]+.[0-9]+"

jobs:
  publish-binary:
    runs-on: macos-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build
        run: |
          swift build -c release --arch arm64 --product swallowlint¥
          mkdir -p "$(TEMPORARY_FOLDER)"
          cp -f ".build/release/swallowlint" "$(TEMPORARY_FOLDER)/swallow-lint"
          cp -f "LICENSE" "$(TEMPORARY_FOLDER)"
          (cd $(TEMPORARY_FOLDER); zip -r - LICENSE swallow-lint) > "./portable_swallowlint.zip"
          rm -r "$(TEMPORARY_FOLDER)"
        env:
          TEMPORARY_FOLDER: ./tmp_swallowlint
      - name: Release Binary
        uses: softprops/action-gh-release@v1
        with:
          draft: true
          files: portable_swallowlint.zip
