name: Release

on:
  push:
    tags:
      - "[0-9]+.[0-9]+.[0-9]+"

jobs:
  publish-binary:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build
        run: |
          swift build -c release --arch arm64 --target swallowlint
          tar -czf swallowlint.tar.gz .build/release/swallowlint
      - name: Release Binary
        uses: softprops/action-gh-release@v1
        with:
          draft: true
          files: swallowlint.tar.gz
