name: "SwallowLint Tests"
on:
  push:
    branches:
      - "main"
      - "develop"
  pull_request:
  workflow_dispatch:

jobs:
  macos:
    name: Test
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build
        run: swift build
      - name: Run tests
        run: swift test
